# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bitcoin DSL Docs
email: kp@opdup.com
description: >- # this means to ignore newlines until "baseurl:"
  Bitcoin DSL documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitcoin-dsl.opdup.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jungly
github_username:  pool2win

# Build settings
theme: just-the-docs
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  overview:
    permalink: ":collection/:path"
    output: true
  # transactions:
  #   permalink: ":collection/:path"
  #   output: true    
  # script-sig:
  #   permalink: ":collection/:path"
  #   output: true    
  # script-pub-key:
  #   permalink: ":collection/:path"
  #   output: true
  examples:
    permalink: ":collection/:path"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    overview:
      name: DSL Features
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
    # transactions:
    #   name: Transactions
    # scriptsig:
    #   name: Script Sig
    # scriptpubkey:
    #   name: Script Pub Key
    examples:
      name: Examples

mermaid:
  version: "10.8.0"

favicon_ico: "/assets/img/dsl.png"
